// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BugTestQualityAssessmentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bugTestQualityAssessment() {
    driver.get("http://localhost/Thoth/quality_assessment/83");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".even > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".even > td:nth-child(2)")).click();
    driver.findElement(By.id("QQ1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("QQ1"));
      dropdown.findElement(By.xpath("//option[. = 'M']")).click();
    }
    driver.findElement(By.cssSelector(".swal2-confirm")).click();
    driver.findElement(By.id("modal_paper_qa")).click();
    driver.findElement(By.linkText("Planning")).click();
    {
      WebElement element = driver.findElement(By.linkText("Planning"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".nav-item:nth-child(7) > .nav-link")).click();
    driver.findElement(By.cssSelector("td:nth-child(6) .fas")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("td:nth-child(6) .fas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("edit_desc_qa")).click();
    driver.findElement(By.id("edit_desc_qa")).sendKeys("Mudança");
    driver.findElement(By.id("edit_desc_qa")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Save")).click();
    {
      WebElement element = driver.findElement(By.linkText("Save"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".swal2-confirm")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) .btn-warning")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) .btn-warning"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("edit_score_rule")).click();
    driver.findElement(By.id("edit_score_rule")).sendKeys("Médio");
    driver.findElement(By.linkText("Save")).click();
    {
      WebElement element = driver.findElement(By.linkText("Save"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".swal2-confirm")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) .btn-warning")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) .btn-warning"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("edit_score_rule")).click();
    driver.findElement(By.id("edit_score_rule")).sendKeys("Alta");
    driver.findElement(By.linkText("Save")).click();
    driver.findElement(By.cssSelector(".swal2-confirm")).click();
    driver.findElement(By.linkText("Conducting")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) > .nav-link")).click();
    driver.findElement(By.cssSelector(".even > td:nth-child(3)")).click();
    driver.findElement(By.id("modal_paper_qa")).click();
  }
}
