name: Main Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setting up PHP
        uses: ./.github/actions/php

      - name: Installing Composer
        run: |
          git update-index --chmod=+x application/third_party/vendor/bin/phpunit
          composer install --no-ansi --no-interaction --no-suggest --prefer-dist --ignore-platform-reqs
          composer dumpautoload

      - name: Running PHPUnit
        run: |
          git update-index --chmod=+x application/third_party/vendor/bin/phpunit
          sudo vendor/bin/phpunit  application/tests/
